/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DramasRouteImport } from './routes/dramas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DramasIndexRouteImport } from './routes/dramas.index'
import { Route as ProfileWatchlistRouteImport } from './routes/profile.watchlist'
import { Route as ProfileFavoritesRouteImport } from './routes/profile.favorites'
import { Route as DramasDramaIdRouteImport } from './routes/dramas.$dramaId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as DramasDramaSlugEpisodeNumberRouteImport } from './routes/dramas.$dramaSlug.$episodeNumber'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasRoute = DramasRouteImport.update({
  id: '/dramas',
  path: '/dramas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasIndexRoute = DramasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DramasRoute,
} as any)
const ProfileWatchlistRoute = ProfileWatchlistRouteImport.update({
  id: '/profile/watchlist',
  path: '/profile/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFavoritesRoute = ProfileFavoritesRouteImport.update({
  id: '/profile/favorites',
  path: '/profile/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasDramaIdRoute = DramasDramaIdRouteImport.update({
  id: '/$dramaId',
  path: '/$dramaId',
  getParentRoute: () => DramasRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasDramaSlugEpisodeNumberRoute =
  DramasDramaSlugEpisodeNumberRouteImport.update({
    id: '/$dramaSlug/$episodeNumber',
    path: '/$dramaSlug/$episodeNumber',
    getParentRoute: () => DramasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dramas': typeof DramasRouteWithChildren
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dramas/$dramaId': typeof DramasDramaIdRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/watchlist': typeof ProfileWatchlistRoute
  '/dramas/': typeof DramasIndexRoute
  '/dramas/$dramaSlug/$episodeNumber': typeof DramasDramaSlugEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dramas/$dramaId': typeof DramasDramaIdRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/watchlist': typeof ProfileWatchlistRoute
  '/dramas': typeof DramasIndexRoute
  '/dramas/$dramaSlug/$episodeNumber': typeof DramasDramaSlugEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dramas': typeof DramasRouteWithChildren
  '/history': typeof HistoryRoute
  '/watchlist': typeof WatchlistRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dramas/$dramaId': typeof DramasDramaIdRoute
  '/profile/favorites': typeof ProfileFavoritesRoute
  '/profile/watchlist': typeof ProfileWatchlistRoute
  '/dramas/': typeof DramasIndexRoute
  '/dramas/$dramaSlug/$episodeNumber': typeof DramasDramaSlugEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dramas'
    | '/history'
    | '/watchlist'
    | '/auth/signin'
    | '/auth/signup'
    | '/dramas/$dramaId'
    | '/profile/favorites'
    | '/profile/watchlist'
    | '/dramas/'
    | '/dramas/$dramaSlug/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/watchlist'
    | '/auth/signin'
    | '/auth/signup'
    | '/dramas/$dramaId'
    | '/profile/favorites'
    | '/profile/watchlist'
    | '/dramas'
    | '/dramas/$dramaSlug/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/dramas'
    | '/history'
    | '/watchlist'
    | '/auth/signin'
    | '/auth/signup'
    | '/dramas/$dramaId'
    | '/profile/favorites'
    | '/profile/watchlist'
    | '/dramas/'
    | '/dramas/$dramaSlug/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DramasRoute: typeof DramasRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  WatchlistRoute: typeof WatchlistRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProfileFavoritesRoute: typeof ProfileFavoritesRoute
  ProfileWatchlistRoute: typeof ProfileWatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas': {
      id: '/dramas'
      path: '/dramas'
      fullPath: '/dramas'
      preLoaderRoute: typeof DramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas/': {
      id: '/dramas/'
      path: '/'
      fullPath: '/dramas/'
      preLoaderRoute: typeof DramasIndexRouteImport
      parentRoute: typeof DramasRoute
    }
    '/profile/watchlist': {
      id: '/profile/watchlist'
      path: '/profile/watchlist'
      fullPath: '/profile/watchlist'
      preLoaderRoute: typeof ProfileWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/favorites': {
      id: '/profile/favorites'
      path: '/profile/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof ProfileFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas/$dramaId': {
      id: '/dramas/$dramaId'
      path: '/$dramaId'
      fullPath: '/dramas/$dramaId'
      preLoaderRoute: typeof DramasDramaIdRouteImport
      parentRoute: typeof DramasRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas/$dramaSlug/$episodeNumber': {
      id: '/dramas/$dramaSlug/$episodeNumber'
      path: '/$dramaSlug/$episodeNumber'
      fullPath: '/dramas/$dramaSlug/$episodeNumber'
      preLoaderRoute: typeof DramasDramaSlugEpisodeNumberRouteImport
      parentRoute: typeof DramasRoute
    }
  }
}

interface DramasRouteChildren {
  DramasDramaIdRoute: typeof DramasDramaIdRoute
  DramasIndexRoute: typeof DramasIndexRoute
  DramasDramaSlugEpisodeNumberRoute: typeof DramasDramaSlugEpisodeNumberRoute
}

const DramasRouteChildren: DramasRouteChildren = {
  DramasDramaIdRoute: DramasDramaIdRoute,
  DramasIndexRoute: DramasIndexRoute,
  DramasDramaSlugEpisodeNumberRoute: DramasDramaSlugEpisodeNumberRoute,
}

const DramasRouteWithChildren =
  DramasRoute._addFileChildren(DramasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DramasRoute: DramasRouteWithChildren,
  HistoryRoute: HistoryRoute,
  WatchlistRoute: WatchlistRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProfileFavoritesRoute: ProfileFavoritesRoute,
  ProfileWatchlistRoute: ProfileWatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
